config/routes.rb
class SubdomainPresent
    def self.matches?(request)
        subdomains = %w{ https:// www admin }
        request.subdomain.present? && !subdomains.include?(request.subdomain)
    end
end

class SubdomainBlank
    def self.matches?(request)
        subdomains = %w{ https:// www admin }
        request.subdomain.blank? || subdomains.include?(request.subdomain)
    end
end

Rails.application.routes.draw do

  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users



    constraints(SubdomainBlank) do
        root 'visitors#new'
        get 'contact-us', to: 'contacts#new', as: 'new_contact'
        resources :contacts, only: :create
        resources :visitors, only: [:new, :create, :index]
        get 'features', to: 'pages#features'
        get 'pricing', to: 'pages#pricing'
    end

    constraints(SubdomainPresent) do
        root 'projects#index'
        resources :projects, only: [:index, :show, :new, :create] do
        resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
          resources :comments
          collection do
              post :import
          end
        end

          scope module: "users" do
            resources :companies
            resources :lists
            resources :cards
            resources :deals
            resources :invites
            resources :activities
          end
        end
      end
    end

app/models/visitor.rb
class Visitor
  include ActiveModel::Model
  attr_accessor :email, :string
  validates_presence_of :email
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    list_id = Rails.application.secrets.mailchimp_list_id
    result = mailchimp.lists(list_id).members.create(
      body: {
        email_address: self.email,
        status: 'subscribed'
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end

  def new
    @visitor = Visitor.new
    if Plan.first == nil
      Plan.create(name: 'basic', price: 0)
      Plan.create(name: 'pro', price: 49)
      Plan.create(name: 'invite', price: 0)
    end
    # GET request for which / is our home page
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
    @invite_plan = Plan.find(3)
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_url(subdomain: 'www')
    else
      flash[:danger] = "Please add email address"
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end

end

app/views/visitors/new.html.erb
<div class="container-fluid" id="News">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2"><br/>
      <h2 class="text-center news">Make your autoshop management easier than ever.</h2>
      <h3 class="text-center" style="padding-bottom:20px;">Be more efficient in seconds</h3>
        <div class="col-sm-8 col-sm-offset-2"><br/>
          <ul class="inline" style="list-style-type:none;text-align:center">
            <li><%= link_to "Try for Free", signup_path(plan: @basic_plan.id), class: 'btn btn-default-outline btn-lg' %></li>
            <li style="padding-top:20px;padding-bottom:10px;"><%= link_to "Request a Demo", new_contact_path, class: 'btn btn-default-outline btn-lg' %>
            </li>
            <br/>
          </ul>
        </div>
    </div>
  </div>
</div>
<div style="padding: 10px 40px;" class="container-fluid">
  <div class="row">
    <div style="text-align:center" class="col-sm-6 col-sm-offset-3">
      <h2>Autoshop management made simple</h2>
      <h4>Nomad Auto is very simple tool to use, has powerful features, and only takes seconds to set up. Start today for free by signing up and inviting the rest of your team. We offer an all-in-one tool for your autoshop business.</h4>
      <h4>Nomad Auto was written to assist auto-mechanic service companies with their customer relationships and business processes. 
      It will help to keep track of customers vehicles and the repairs that have been completed. 
      It will generate and print invoices, help find parts and provide repair estimates.</h4>
      <div style="text-algin:center; padding-top:40px;"><%= link_to "Create Free Account", signup_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg' %></li>
    </div>
  </div>
  </div>
</div>

<div class="container-fluid text-center">
  <h2>SERVICES</h2>
  <h4>What we offer</h4>
  <br>

<div style="padding:25px;margin:0px 50px 0px 50px;background-color:#FFF" class="container-fluid">
  
  <div class="row">
    <div class="col-md-2 col-md-offset-2">
          <div style="font-size:3em;text-align:center;">
            <i style="font-size: 130px" class="glyphicon glyphicon-tasks logo"></i>
          </div>
          <h4 style="text-align:center">Work Tasks</h2>
          <h4>Help assign tasks and keep your team organized. Keep track of whats completed and what still needs done. </h4>
    </div>
 
    <div class="col-md-2">
      <div style="font-size:3em;text-align:center;">
          <i style="font-size: 130px" class="glyphicon glyphicon-road logo"></i>
        </div>
        <h4 style="text-align:center">Vehicle Raodmap</h2>
        <h4>Keep track of all the vehicles you have worked on. And help alert customers of common vehicle problems.</h4>
    </div>

    <div class="col-md-2">
      <div style="font-size:3em;text-align:center;">
          <i style="font-size: 130px" class="glyphicon glyphicon-pencil logo"></i>
        </div>
        <h4 style="text-align:center">Invoice Generation</h2>
        <h4>Genereate and print invoices its very quick and easy. Contain a history of all invoice records.</h4>
    </div>

    <div class="col-md-2">
      <div style="font-size:3em;text-align:center;">
          <i style="font-size: 130px" class="glyphicon glyphicon-search logo"></i>
        </div>
        <h4 style="text-align:center">Part Finder</h2>
        <h4>Search for part numbers and find good deals.</h4>
    </div>

  </div>

    </br></br></br>
    
  <div class="row">

    <div class="col-md-2 col-md-offset-2">
      <div style="font-size:3em;text-align:center;">
        <i style="font-size: 130px" class="glyphicon glyphicon-barcode logo"></i>
      </div>
      <h4 style="text-align:center">Repair Estimates</h2>
      <h4>Build out repair estimates for your customers.</h4>
    </div>

  <div class="col-md-2">
    <div style="font-size:3em;text-align:center;">
      <i style="font-size: 130px" class="fa fa-mobile logo"></i>
    </div>
    <h4 style="text-align:center">Mobile Friendly</h2>
    <h4>Use with your phone from anywhere.</h4>
  </div>

  <div class="col-md-2">
    <div style="font-size:3em;text-align:center;">
      <i style="font-size: 130px" class="fa fa-users logo"></i>
    </div>
    <h4 style="text-align:center">Team Collaboration</h2>
    <h4>Work as a team all with your own profile.</h4>

  </div>

  <div class="col-md-2">
    <div style="font-size:3em; text-align:center;">
      <i style="font-size: 130px" class="fa fa-database logo"></i>
    </div>
    <h4 style="text-align:center">Data Normalization</h2>
    <h4>Start keeping your records organized.</h4>
  </div>

  </div>
</div>

</div>

<div class="container-fluid" id="SignUp">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="text-center">
          <h3 class="text-center news">Subscribe to our newsletter</h3>

          <%= form_for @visitor do |f| %>
            <%= f.text_field :email, label: false, :placeholder => 'Your email address...', class: 'form-control visitors' %>
            <br/>
            <%= f.submit "Subscribe", :class => "btn btn-default-outline btn-lg" %>
          <% end %>
        </div>
    </div>
  </div>
</div>