config/routes.rb
class SubdomainPresent
    def self.matches?(request)
        subdomains = %w{ https:// www admin }
        request.subdomain.present? && !subdomains.include?(request.subdomain)
    end
end

class SubdomainBlank
    def self.matches?(request)
        subdomains = %w{ https:// www admin }
        request.subdomain.blank? || subdomains.include?(request.subdomain)
    end
end

Rails.application.routes.draw do

  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users



    constraints(SubdomainBlank) do
        root 'visitors#new'
        get 'contact-us', to: 'contacts#new', as: 'new_contact'
        resources :contacts, only: :create
        resources :visitors, only: [:new, :create, :index]
        get 'features', to: 'pages#features'
        get 'pricing', to: 'pages#pricing'
    end

    constraints(SubdomainPresent) do
        root 'projects#index'
        resources :projects, only: [:index, :show, :new, :create] do
        resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
          resources :comments
          collection do
              post :import
          end
        end

          scope module: "users" do
            resources :companies
            resources :lists
            resources :cards
            resources :deals
            resources :invites
            resources :activities
          end
        end
      end
    end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user
  belongs_to :project

  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :comments, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  def self.assign_from_row(row)
      task = Task.where(project_id: row[:project_id],
                        title: row[:title],
                        owner: row[:owner],
                        status: row[:status],
                        priority: row[:priority],
                        description: row[:description]).first_or_initialize
      task
  end



  def self.import(file)
    counter = 0
    CSV.foreach(file.pathmap, headers: true, header_converters: :symbol) do |row|
      task = Task.assign_from_row(row)
      if task.save
        counter += 1
      else
        puts "#{task.title} - #{task.errors.full_messages.join(", ")}"
      end
    end
    counter
  end

end

app/controllers/tasks_controller.rb
class TasksController < UsersController
  before_action :trial_expired?
  skip_before_filter :verify_authenticity_token, only: [:index, :show]

  def index
    @project = Project.find(params[:project_id])
    authorize @project
    user = User.all
    if Task.where(project_id: @project)
      @tasks = @project.tasks.all

      @tasks = @project.tasks.where(status: params["status"]) if params["status"].present?
      @tasks = @project.tasks.where(priority: params["priority"]) if params["priority"].present?
      @tasks = @project.tasks.where(user: params["user"]) if params["user"].present?

      @tasks = @project.tasks.order(sort_column + ' ' + sort_direction) if params["sort"].present?
    end
  end

  def show
    #1st you retrieve the project thanks to params[:project_id]
    @project = Project.find(params[:project_id])
    #2nd you retrieve the tasks thanks to params[:id]
    #@task = project.tasks.find(params[:id])
    #@task = @project.tasks.find_by!(permalink: params[:id])
    @task = @project.tasks.find(params[:id])
    #authorize @task

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end

  end

  def new
    #1st you retrieve the project thanks to params[:project_id]
    @project = Project.find(params[:project_id])

    #2nd you get all the tasks of this project
    @task = @project.tasks.build
    authorize @task

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
    #@task = Task.new
  end

  def create
    #1st you retrieve the project thanks to params[:project_id]
    @project = Project.find(params[:project_id])

    #2nd you create the task with arguments in params[:task]
    @task = @project.tasks.create(task_params)


    respond_to do |format|
      if @task.save
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource task
        format.html { redirect_to project_tasks_path(@project), :notice => 'Task was successfully created.' }
        #the key :location is associated to an array in order to build the correct route to the nested resource task
        format.xml  { render :xml => @task, :status => :created, :location => [@task.project, @task] }

        track_activity @task

      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
    # if @task.save
    #   # Store form fields via paramaters, into variables
    #   title = params[:task][:title]
    #   description = params[:task][:description]
    #   status = params[:task][:status]
    #   priority = params[:task][:priority]
    #   flash[:success] = "Record Saved."

    #   redirect_to project_tasks_path
    # else
    #   redirect_to project_tasks_path
    # end
  end

  def edit
    @project = Project.find(params[:project_id])

    @task = @project.tasks.find(params[:id])
  end

  def update
    #1st you retrieve the post thanks to params[:post_id]
    @project = Project.find(params[:project_id])
    #2nd you retrieve the comment thanks to params[:id]
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(task_params)
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to project_tasks_path(@project), :notice => 'Task was successfully updated.' }
        flash[:success] = "Your task has been updated"
        format.xml  { head :ok }
        track_activity @task

      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
    # if @task.update_attributes(task_params)
    #   flash[:success] = "Profile updated"
    #   redirect_to project_tasks_path
    # else
    #   render 'edit'
    # end
  end



  def destroy
    #1st you retrieve the project thanks to params[:project_id]
    @project = Project.find(params[:project_id])
    #2nd you retrieve the task thanks to params[:id]
    @task = Task.find(params[:id])

    if @task.destroy
      redirect_to project_tasks_path(@project)
    end
  end

  def import
    user = User.find(session[:user_id])
    count = user.tasks.import params[:file]
    redirect_to project_tasks_path, notice: "Imported #{count} users"
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status, :priority, :owner, :project_id, :user_id)
  end

  def sort_column
    params[:sort] || "title"
  end

  def sort_direction
    params[:direction] || "asc"
  end
end

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task]) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :status %>
    <%= f.select :status, options_for_select([['Open'],['Pending'],['Closed']]), class: "form-control"  %>

    <%= f.label :priority %>
    <%= f.select :priority, options_for_select([['High'],['Medium'],['Low']]), {}, class: "form-control" %>

    <%= f.label :owner %>
    <% options_from_collection_for_select(current_account.user_users, :name, :name) %>
    <%= f.collection_select(:owner, current_account.user_users, :name, :name) %>

    <%= f.hidden_field :user_id, value: current_user.id, readonly: true, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
    </br>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>
<td><%= link_to "delete", [@task.project, @task, @activities], method: :delete, data: { confirm: "Are you sure?" } %></td>
<td><%= link_to "Back", project_tasks_path(@project) %></td>

app/views/tasks/edit.html.erb
<%= render 'users/sidebar' %></br>

<div class="container-fluid">
  <div class="row">
    <div class="well">
      <h3>Manage this task for your scrum board</h3>
        <%= render 'form' %>
    </div>
  <div>
</div>

app/views/tasks/index.html.erb
<%= render 'users/sidebar' %></br>
  <!-- Page content -->
  <div id="page-content-wrapper">
    <!-- Keep all page content within the page-content inset div! -->
    <div class="page-content inset">
      <div class="row">
      <div class="container-fluid" id="Tasks">
        <div class="well">
          <%if Task.where(project_id: @project) %>
            <div class="col-xs-12 col-md-6 col-md-offset-0">
              <h4>Priorities Graph</h4>
              <%= bar_chart @project.tasks.group(:priority).count %>
            </div>
            <div class="col-xs-12 col-md-6 col-md-offset-0">
              <h4>Status Graph</h4>
              <%= line_chart @project.tasks.group(:status).count %>  </br></br>
            </div>
          <% end %>
        <div class="col-md-12 col-md-offset-0">
        <%= link_to "Create New Ticket", new_project_task_path(), class: 'btn btn-default', id: "addtask" %>
        </div>
        <%= form_tag project_tasks_path, method: :get, class: "form-inline" do %>
            <div class="col-md-4">
            <%= label_tag "Status" %>
            <%= select_tag("status", options_for_select([['Open'],['Pending'],['Closed']]), :multiple => true, class: "filterbox" ) %>
            </div>
            <div class="col-md-4">
            <%= label_tag "Priority" %>
            <%= select_tag("priority", options_for_select([['High'],['Medium'],['Low']]), :multiple => true, class: "filterbox" ) %>
            </div>
            <div class="col-md-4">
            <%= label_tag "User" %>
            <%= select_tag "user", options_from_collection_for_select(current_account.user_users, 'id', 'name'), :multiple => true, class: "filterbox" %>
            </div>
            <div class="col-md-6">
            <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
            </div>
            <div class="col-md-6">
            <%= link_to "Reset", project_tasks_path, class: 'btn btn-default' %>
            </div>
        <% end %>
            <div class="col-md-12">
              <table class="table">
                <thead>
                 <tr id="table_sort">
                   <th class="center"><%= sortable "title" %></th>
                   <th class="center"><%= sortable "status" %></th>
                   <th class="center"><%= sortable "priority" %></th>
                   <th class="center"><%= sortable "user" %></th>
                   <th class="center"><%= sortable "created_at" %></th>
                   <th class="center"><%= sortable "updated_at" %></th>
                 </tr>
                </thead>
                <tbody>
                    <%if Task.where(project_id: @project) %>
                      <% @tasks.each do |task| %>
                        <tr>
                          <td class="center" style="vertical-align:middle"><%= link_to task.title, project_task_path(@project, task) %></td>
                          <td class="center" style="vertical-align:middle"><%= task.status %></td>
                          <td class="center" style="vertical-align:middle"><%= task.priority %></td>
                          <td class="center" style="vertical-align:middle"><%= if task.owner == nil
                                                                                  task.user.name
                                                                              else
                                                                                  task.owner
                                                                              end %></td>
                          <td class="center" style="vertical-align:middle"><%= "#{time_ago_in_words(Time.at(task.created_at.to_i))} ago" %></td>
                          <td class="center" style="vertical-align:middle"><%= "#{time_ago_in_words(Time.at(task.updated_at.to_i))} ago" %></td>
                        </tr>
                      <% end %>
                    <% end %>
                </tbody>
              </table>

              <%= form_tag import_project_tasks_path do %>
                   <%= file_field_tag :file %>
                   <%= submit_tag "Upload" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render 'users/sidebar' %></br>

<div class="container-fluid">
  <div class="row">
    <div class="well">
      <h3>Add a new ticket to your list</h3>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<%= render 'users/sidebar' %></br>

<div class="container-fluid">
  <div class="row">
    <div class="well">
    <p id="notice"><%= notice %></p>

      <div class="card">
        <div class="card-header">
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><h3>Title: <%= @task.title %></h3></li>
          <li class="list-group-item"><h3>Priority: <%= @task.priority %></h3></li>
          <li class="list-group-item"><h3>Owner: <%= @task.owner %></h3></li>
          <li class="list-group-item"><h3>Description: <%= @task.description %></h3></li>
        </br>
          <%= link_to "Delete", [@task.project, @task, @activities],
                      class: 'btn btn-default',
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>

          <%= link_to "Edit", edit_project_task_path(@project),
                      class: 'btn btn-default' %>
          <%= link_to "Back", project_tasks_path(@project),
                      class: 'btn btn-default' %>
        </ul>
       </div>
      </div>
    </div>
    <div class="well">
      <h3><%= @task.comments.count %> Comments</h3>
       <%= render @task.comments %>

      <h4>Add a comment:</h4>
      <%= render 'comments/form' %>
    </div>
  <div>
</div>