config/routes.rb
class SubdomainPresent
    def self.matches?(request)
        subdomains = %w{ https:// www admin }
        request.subdomain.present? && !subdomains.include?(request.subdomain)
    end
end

class SubdomainBlank
    def self.matches?(request)
        subdomains = %w{ https:// www admin }
        request.subdomain.blank? || subdomains.include?(request.subdomain)
    end
end

Rails.application.routes.draw do

  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users



    constraints(SubdomainBlank) do
        root 'visitors#new'
        get 'contact-us', to: 'contacts#new', as: 'new_contact'
        resources :contacts, only: :create
        resources :visitors, only: [:new, :create, :index]
        get 'features', to: 'pages#features'
        get 'pricing', to: 'pages#pricing'
    end

    constraints(SubdomainPresent) do
        root 'projects#index'
        resources :projects, only: [:index, :show, :new, :create] do
        resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
          resources :comments
          collection do
              post :import
          end
        end

          scope module: "users" do
            resources :companies
            resources :lists
            resources :cards
            resources :deals
            resources :invites
            resources :activities
          end
        end
      end
    end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  #validates :title, :presence => true, :length => { :minimum => 5 }

  has_many :companies, dependent: :destroy
  has_many :deals, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :invites, dependent: :destroy
  accepts_nested_attributes_for :tasks

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
skip_before_filter :verify_authenticity_token, only: [:index, :show]

  def index
    # GET request for which / is our home page
    # @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
    # @invite_plan = Plan.find(3)
    if Project.exists?(user: current_account)
      @projects = current_account.user_projects
    end

  end

  def show
    @project = Project.find(params[:id])
    authorize @project
  end

  def new
    @project = Project.new
    #@task = Task.new(project_id: params[:project_id])
  end

  def create
    @project = current_account.projects.build(project_params)
     if @project.save
       flash[:notice] = "#{@project.title} is processing."
       redirect_to projects_path
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :details, :task_id, :deal_id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, html: { class: 'form-horizontal' }) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>

    <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>
<td><%= link_to "delete", @project, method: :delete, data: { confirm: "Are you sure?" } %></td>

app/views/projects/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Teams</h1>
      <div class="well">
        <h2><%= link_to 'Create New Team', new_project_path, class: 'btn btn-default btn-lg' %></h2>
        <p> trial period will expire in <span style="color:red"><%= remaining_days %> Days. </span><%= link_to "Suscribe Now!", signup_path(plan: @pro_plan.id) %></p>
        <table class="table table-striped">
          <% current_account.projects.each do |project| %>
            <tr>
              <td><%= link_to project.title, project_tasks_path(project) %></td>
              <td><%= project.details %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      </br>
      <h3>Add a new support group</h3>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="well projects">

    </div>
  </div>
</div>